name: pos_and_remittance
description: "A POS and Remittance Flutter application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # SQLite Database
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.3
  crypto: ^3.0.7
  
  # Web support
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^1.1.1
  
  # Utilities
  intl: ^0.18.1
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
